USE [master]
GO

/****** Object:  Database [EFDB]    Script Date: 6/15/2022 11:48:53 AM ******/
CREATE DATABASE [EFDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EFDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\EFDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EFDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\EFDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EFDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EFDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EFDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EFDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EFDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EFDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [EFDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EFDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EFDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EFDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EFDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EFDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EFDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EFDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EFDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EFDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EFDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EFDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EFDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EFDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EFDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EFDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EFDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EFDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EFDB] SET  MULTI_USER 
GO

ALTER DATABASE [EFDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EFDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EFDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EFDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EFDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EFDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EFDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EFDB] SET  READ_WRITE 
GO

